<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>workshopclick</AssemblyName>
    <RootNamespace>Calloatti.WorkshopClick</RootNamespace>
    <TimberbornPath>C:\Program Files (x86)\Steam\steamapps\common\timberborn_public\Timberborn_Data\Managed</TimberbornPath>
  </PropertyGroup>

  <Import Project="CommonModSettings.props" />

</Project>


